Change `crossdomain` to `permittedCrossDomainPolicies`
helmetjs/helmetjs.github.io pull request #39
Opened 2019-02-15 20:10 UTC by victor-perez

When I was reading the docs I was trying
```
app.user(helmet({
 crossdomain: true
}))
```
only after reading the source code I found out that the module is called `permittedCrossDomainPolicies` inside helmet.

2019-02-15 23:19 UTC, EvanHahn commented
Thanks--I'll take a look at this soon.

2019-03-05 20:36 UTC, EvanHahn requested changes
Good catch—thanks for spotting this.

One small thing: can you make sure the table is alphabetized after this change? Looks like it should go right before referrerPolicy.

2019-03-17 17:36 UTC, victor-perez commented
> Good catch—thanks for spotting this.
> 
> One small thing: can you make sure the table is alphabetized after this change? Looks like it should go right before referrerPolicy.

Changed

2019-03-17 18:43 UTC, EvanHahn approved these changes

2019-03-17 18:44 UTC, merged

2019-03-17 18:44 UTC, EvanHahn commented
Thanks! Feel free to add yourself to the [contributors page](https://github.com/helmetjs/helmetjs.github.io/blob/master/contributors/index.md).