Spanish translation of the docs
helmetjs/helmetjs.github.io pull request #44
Opened 2020-02-13 07:52 UTC by LautaroJayat

+ Added Spanish translations for all the index.md files in the `/docs/`
+ Added a link at the bottom of the index.md file inside the root folder.
+ The translation will also be revised for further improvements

I think that is ready to merge.

2020-02-13 14:13 UTC, EvanHahn commented
¡Gracias! I will look at this soon.

2020-02-13 14:44 UTC, LautaroJayat commented
Cool!
Let me know if you wan't any correction, or extra information, or something ;)

2020-04-08 20:11 UTC, EvanHahn requested changes
In English: Thanks so much! I have reviewed a few files but there's still more for me to look at. Could you fix these comments while I review the rest?

En español: ¡Muchas gracias! Revisé algunos de los archivos pero todavía hay más que tengo revisar. Arregles mis commentos, por favor.

2020-04-08 20:11 UTC, EvanHahn commented on index.md
> +To see the documentation in other languages
Could you remove this? I will link to Spanish documentation in a separate commit.

2020-04-08 20:11 UTC, EvanHahn commented on translations/es/crossdomain/index.md
> +Adobe Flash y Adobe Acrobat pueden cargar contenido en tu dominio incluso desde otros sitios (en otras palabtas, "*cross-domain*"). Esto podría causar inesperadas filtraciones de datos o un uso exces
*palabtas* → *palabras*?

2020-04-08 20:11 UTC, EvanHahn commented on translations/es/crossdomain/index.md
> +La cabecera `X-Permitted-Cross-Domain-Policies` dice a los clientes Flash and Acrobat qué políticas de dominio cruzado ("*cross-domain*) pueden usar. Si no quieres que carguen contenido desde tu domi
*Ejemplo* → *ejemplo*?

2020-04-08 20:11 UTC, EvanHahn commented on translations/es/crossdomain/index.md
> +Si flash carga algo desde tu sitio y ve eso, entonces sabrá que no debe cargar contenido desde tu dominio.
*flash* → *Flash*?

2020-04-08 20:11 UTC, EvanHahn commented on translations/es/crossdomain/index.md
> +Para más información:
¿Deberíamos mencionar que estos enlaces son en íngles? (No sé.)

2020-04-08 20:11 UTC, EvanHahn commented on translations/es/csp/index.md
> +Brevemente: el módulo CSP setea la cabecera `Content-Security-Policy`, la cual puede ayudar a proteger contra inyecciones maliciosas de Javascript, CSS, *pluguins*, y más.
1. *Javascript* → *JavaScript*? This needs to be fixed everywhere.
1. *pluguins* → *plugins*?

2020-04-08 20:11 UTC, EvanHahn commented on translations/es/csp/index.md
> +El ataque más sucio es probablemente el *cross-site scripting* (XSS), el cual ocurre cuando un hacker pone código malicioso en tu sitio. Si yo puedo ejecutar Javascript en tu página, entonces puedo h
¿Deberíamos poner en cursiva "*cookies*"?

2020-04-08 20:11 UTC, EvanHahn commented on translations/es/csp/index.md
> +Existen otras cosas que los atacantes pueden hacer, incluso si no pueden ejecutar Javascript. por ejemplo, si uno pudiera poner una pequeña imagen en tu sitio, 1x1 y transparente, podría tener una bu
1. "por ejemplo" → "Por ejemplo"
1. `http` → `https`. (Necesito hacerlo en la documentación en íngles, tambien. Hice #47.)
1. "flash" → "Flash"

2020-04-08 20:11 UTC, EvanHahn commented on translations/es/csp/index.md
> +La Cabecera
"Cabecera" → "cabecera"

2020-04-08 20:11 UTC, EvanHahn commented on translations/es/csp/index.md
> +Una de las complicaciones acerca de éstas ataques de inyección de código es que los navegadores no saben qué es bueno y qué es malo. ¿Cómo podría diferenciar entre un archivo de Javascript legítimo y
1. ¿"yu" es un error de tipografía?
1. Hay un extra `"` aquí.

2020-04-08 20:11 UTC, EvanHahn commented on translations/es/csp/index.md
> +La mayoría de los navegadores modernos soportan la cabecera llamada `Content-Security-Policy`, la cual efectivamente es una lista blanca de las cosas que tienen permitido estar en tu página. Podes pe
*pluguins* → *plugins*?

2020-04-08 20:11 UTC, EvanHahn commented on translations/es/csp/index.md
> +Ahora `'self'` y `maxcdn.bootstrapcdn.com` en nuestra lista blanca. los usuarios podrán cargar CSS desde ahí, pero desde ningún otro lugar. Los usuarios ni siquiera tendrán permitido cargar Javascrio
1. "en nuestra lista blanca" → "están en nuestra lista blanca"?
1. "los usarios" → "Los usarios"
1. "Javascriot" → "JavaScript"

2020-04-08 20:11 UTC, EvanHahn commented on translations/es/csp/index.md
> +    console.log('CSP Violation: ', req.body)
¿Deberíamos traducir estos `console.log`s?

2020-04-08 20:11 UTC, EvanHahn commented on translations/es/csp/index.md
> +Tambén puedes asignar esto a una función para decidir de manera dinámica cuándo usar el modo `reportOnly`. Puedes usar ésto como un disyuntor dinámico. En éste caso, la función es llamada usando los
*Tambén* → *También*?

2020-04-08 20:11 UTC, EvanHahn commented on translations/es/csp/index.md
> +### Browser sniffing (detección de navegadores).
1. ¿Se debe poner en cursiva "Browser sniffing"?
1. Por favor, elimine el punto.

2020-04-08 20:11 UTC, EvanHahn commented on translations/es/csp/index.md
> +Por defecto, éste módulo se fijará en la cabecera `User-Agent` entrante y enviará diferentes cabeceras dependiendo en el navegador detectado. por ejemplo, las versiones previas a Chrome 25 usan una c
"por ejemplo" → "Por ejemplo"

2020-04-08 20:11 UTC, EvanHahn commented on translations/es/dns-prefetch-control/index.md
> +In short: this middleware lets you disable browsers' DNS prefetching by setting the `X-DNS-Prefetch-Control` header.
In English: this file was not translated. Could we translate it (or delete most of it and add a link to [the English docs][0])?

En español: este archivo no está traducido. Quiero que lo traduces (o elimines el contento y añades un elace al [version íngles][0]), por favor.

[0]: https://helmetjs.github.io/docs/dns-prefetch-control/

2020-04-08 20:11 UTC, EvanHahn commented on translations/es/dont-sniff-mimetype/index.md
> +Brevemente: la funcción middleware "*Don't Sniff Mimetype middleware*", `noSniff`, ayuda a prevenir que los navegadores intenten inferir los *MIME type*, lo que puede tener implicancias en la segurid
1. `la funcción middleware "*Don't Sniff Mimetype middleware*"` → `la funcción middleware "*Don't Sniff Mimetype*"`
1. "esto se realiza" → "Esto se realiza"

2020-04-08 20:11 UTC, EvanHahn commented on translations/es/dont-sniff-mimetype/index.md
> +Este *Mime sniffing* puede ser un vector de ataques. un usuario podría subir una archivo con una extensión `.jpg`, pero con HTML en su contenido. Cargar esa página podría causar que el navegador "eje
1. "Mime" → "MIME"
1. "un usuario" → "Un usuario"
1. "pluguin" → "plugin"

2020-04-08 20:11 UTC, EvanHahn commented on translations/es/dont-sniff-mimetype/index.md
> +La Cabecera
"Cabecera" → "cabecera"

2020-04-08 20:11 UTC, EvanHahn commented on translations/es/dont-sniff-mimetype/index.md
> +// Asigna"X-Content-Type-Options: nosniff".
```diff
-// Asigna"X-Content-Type-Options: nosniff".
+// Asigna "X-Content-Type-Options: nosniff".
```

2020-04-08 20:11 UTC, EvanHahn commented on translations/es/expect-ct/index.md
> +La cabecera HTTP `Expect-CT` indica a los navegadores que deben esperar ("*Certificate Transparency*"). Para saber más acerca de *Certificate Transparency y ésta cabecera, ve [este artículo](https://
Necesitamos un `*` después de la palabra "Transparency".

```diff
-Para saber más acerca de *Certificate Transparency y ésta cabecera
+Para saber más acerca de *Certificate Transparency* y ésta cabecera
````

2020-04-14 02:40 UTC, LautaroJayat commented
Sorry pal!
I will correct all of this as soon as possible!

2020-07-29 15:15 UTC, EvanHahn commented
I plan to release Helmet version 4 on 2020-08-02. In that release, I will be removing large sections of the documentation (see #48). That means that this pull request can be _much_ smaller and easier for you to maintain. I wanted to let you know!

I will leave another comment next week after the release is finished.

2020-07-29 20:40 UTC, LautaroJayat commented
@EvanHahn sorry about not making the requested changes, I have been extra busy at work.
I promise that I will read the new documentation and try to translate it. And also make the requested changes so the current version can be translated too.

2020-07-29 22:06 UTC, EvanHahn commented
No problem! Take your time.

2020-08-02 17:00 UTC, EvanHahn commented
Helmet 4 was just released, so there should be a lot less work. Thank you, and take your time!

2022-03-24 00:46 UTC, EvanHahn commented
It's been 2 years since this PR was made. I'm going to close it. I would like to have Spanish translations of the docs, so feel free to make a new one!

2022-03-24 00:46 UTC, closed without merging